defaults:
  - _self_

# Logging configuration
logging:
  level: DEBUG # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_path: ${oc.env:CONTEXT_PATH, "."}/logs/orchard.log # Log fileï¼Œwith date as suffix.

vlm_model:
  _target_: orchard.llm.llm_client.LLMClient
  model: ${oc.env:OPENAI_MODEL}
  base_url: ${oc.env:OPENAI_BASE_URL}
  api_key: ${oc.env:OPENAI_API_KEY}
